# Generated by Django 3.2 on 2021-05-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_bot_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['id']},
        ),
    ]
