# Generated by Django 3.2 on 2021-05-21 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0004_alter_bot_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="creation date"
                    ),
                ),
                ("content", models.TextField(verbose_name="comment text")),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="comment author",
                    ),
                ),
                (
                    "to_bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot",
                        to="mainapp.bot",
                        verbose_name="comment to bot",
                    ),
                ),
            ],
            options={
                "ordering": ["creation_date"],
            },
        ),
    ]
