# Generated by Django 3.2 on 2021-05-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="creation date"
            ),
        ),
    ]
