# Generated by Django 3.2 on 2021-05-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_alter_comment_creation_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_id",
            new_name="author",
        ),
    ]
