# Generated by Django 3.2 on 2021-05-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_bot_auth_user_id"),
        ("mainapp", "0009_alter_comment_author"),
    ]

    operations = []
