# Generated by Django 3.2 on 2021-05-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_rename_auth_user_id_bot_add_by_user"),
        ("mainapp", "0010_merge_20210527_1300"),
    ]

    operations = []
